spring:
  application:
    name: 'kafka-client'
  kafka:
    consumer:
      bootstrap-servers: localhost:9094
      group-id: ${spring.application.name}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    properties:
      schema.registry.url: http://localhost:8081
      specific.avro.reader: true
      value.subject.name.strategy: io.confluent.kafka.serializers.subject.RecordNameStrategy
      auto.register.schemas: false